<x-master-layout>
@php $isAr = app()->getLocale() === 'ar'; @endphp<div class="container-fluid sanad-page">
    <div class="sanad-header"><div><h1 class="sanad-title">{{ app()->getLocale() === "ar" ? "طلباتي" : "My Requests" }}</h1><div class="sanad-muted">{{ app()->getLocale() === "ar" ? "البحث والفلترة والفرز وتصدير الفواتير." : "Search, filter, sort, and export invoices." }}</div></div><a class="sanad-btn" href="{{ route('customer-portal.requests.create') }}">{{ app()->getLocale() === "ar" ? "إنشاء طلب جديد" : "Create New Request" }}</a></div>
    <form class="sanad-card mb-3" method="get"><div class="sanad-card-body row"><div class="col-md-5"><input class="sanad-form-control" name="search" value="{{ request('search') }}" placeholder="{{ app()->getLocale() === "ar" ? "ابحث برقم الطلب أو اسم الخدمة" : "Search request number or service" }}"></div><div class="col-md-5"><select class="sanad-form-control" name="status"><option value="">{{ app()->getLocale() === "ar" ? "جميع الحالات" : "All statuses" }}</option>@foreach(['submitted','pending_review','in_progress','awaiting_customer_action','awaiting_quality_review','completed','closed'] as $status)<option value="{{ $status }}" {{ request('status') === $status ? 'selected' : '' }}>{{ quick_status_label($status) }}</option>@endforeach</select></div><div class="col-md-2"><button class="sanad-btn w-100">{{ app()->getLocale() === "ar" ? "تصفية" : "Filter" }}</button></div></div></form>
    <div class="sanad-card"><div class="sanad-card-body table-responsive"><table class="sanad-table"><thead><tr><th>{{ app()->getLocale() === "ar" ? "الطلب" : "Request" }}</th><th>{{ app()->getLocale() === "ar" ? "الخدمة" : "Service" }}</th><th>{{ app()->getLocale() === "ar" ? "الحالة" : "Status" }}</th><th>{{ app()->getLocale() === "ar" ? "الموعد (SLA)" : "SLA" }}</th><th>{{ app()->getLocale() === "ar" ? "الدفع" : "Payment" }}</th><th>{{ app()->getLocale() === "ar" ? "آخر تحديث" : "Updated" }}</th><th>{{ app()->getLocale() === "ar" ? "الإجراء" : "Action" }}</th></tr></thead><tbody>
        @forelse($requests as $request)
            <tr><td>{{ $request->quick_reference }}</td><td>{{ localized_model_name($request->service) }}</td><td><span class="sanad-badge">{{ quick_status_label($request->sanad_stage ?? $request->status) }}</span></td><td>{{ optional($request->sla_due_at)->format('Y-m-d H:i') ?? '-' }}</td><td>{{ quick_status_label(optional($request->payment)->payment_status ?? 'pending') }}</td><td>{{ optional($request->updated_at)->format('Y-m-d H:i') }}</td><td><a class="sanad-btn secondary" href="{{ route('customer-portal.requests.show', $request->id) }}">{{ app()->getLocale() === "ar" ? "فتح" : "Open" }}</a> @if($request->payment)<a class="sanad-btn ghost" href="{{ route('invoice_pdf', $request->id) }}">{{ app()->getLocale() === "ar" ? "الفاتورة" : "Invoice" }}</a>@endif</td></tr>
        @empty
            <tr><td colspan="7">{{ app()->getLocale() === "ar" ? "لم يتم العثور على أي طلبات." : "No requests found." }}</td></tr>
        @endforelse
    </tbody></table></div></div>
    <div class="mt-3">{{ $requests->links() }}</div>
</div>
</x-master-layout>
